sudo: required
services:
  - docker

script:
  - docker build -t hetsi/node .
  - docker images hetsi/node

before_deploy:
  - docker login -u hetsi -p Chocolate@123

deploy:
  provider: script
  script: docker push hetsi/node
  on:
    branch: master